version: '3.8'

services:
  canadiansolarhttpproxy:
    container_name: CanadianSolarhttpProxy
    build: .
    environment:
      FLASK_APP: src/CanadianSolarHttpProxy.py
      # FLASK_ENV: development
      FLASK_ENV: production
      CANADIAN_SOLAR_AP_IP_ADDRESS: 192.168.0.40
      CANADIAN_SOLAR_AP_USERNAME: user
      CANADIAN_SOLAR_AP_PASSWORD: 12345678
    ports:
      - "8300:5000"
    volumes:
      - .:/app
    restart: always
